language: node_js
sudo: required
node_js:
  - "5.9"

install:
  - npm install -g npm@latest
before_script:
  - npm install -g gulp
  - npm install gulp
  - npm install karma  
  - npm install gulp-karma 
  - npm install karma-jasmine
  - npm install jasmine-core
  - npm install karma-chrome-launcher
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start  
script: gulp test